### ISSUE TITLE
Add dictionary-based clause bank

### ISSUE THREAD

**Issue by perara** [cair/tmu#15]

**Comment by perara** [comment]
@olegranmo I've now implemented a dict based clause bank for the vanilla classifier that works for "sparse" classes.

**Comment by olegranmo** [comment]
Excellent @perara! Does the weight_banks also use dict now?

**Comment by perara** [comment]
This was only clause_banks. I will update so that weight_banks have this structure as well after I've made some tests to ensure that we can support all models.

**Comment by olegranmo** [comment]
Great!

**Comment by perara** [comment]
This is now implemented
