### ISSUE TITLE
Single clause-bank object for all classifiers?

### ISSUE THREAD

**Issue by perara** [cair/tmu#16]
@olegranmo 

Looking at vanilla_classifier they use a list of clause banks instead of a single object. I probably dont understand this properly, but looking at the code is seems like the `self.clause_bank` in coalesced_classifier instead uses the `self.weight_banks` to do updates:
From coalesced:
```python
        self.clause_bank.type_i_feedback(update_p * self.type_i_p, self.s, self.boost_true_positive_feedback,
                                         self.max_included_literals,
                                         self.clause_active * (self.weight_banks[target].get_weights() >= 0),
                                         self.literal_active, self.encoded_X_train, e)```
In the vanilla classifier we have:
```python
            self.clause_banks[target].type_i_feedback(
                update_p=update_p * self.type_i_p,
                s=self.s,
                boost_true_positive_feedback=self.boost_true_positive_feedback,
                max_included_literals=self.max_included_literals,
                clause_active=clause_active[target] * self.positive_clauses,
                literal_active=literal_active,
                encoded_X=self.encoded_X_train,
                e=e
            )
```

Would it be possible to follow the same clause_bank style for `vanilla_classifier` as for rest of the models?

**Comment by olegranmo** [comment]
They are slightly different, with vanilla being more general in the sense that it has multiple clause banks, one clause_bank per label/class. Coalesced, on the other hand, has one shared clause bank for all labels/classes.

**Comment by perara** [comment]
Ah, now I recall. :) Good!
