### ISSUE TITLE
TMRegressor import error

### ISSUE THREAD

**Issue by vegarddale** [cair/tmu#18]
Import error due to missing logging_example.json file.
Python  3.8.13
pip 23.0.1
5.15.0-56-generic #62~20.04.1-Ubuntu SMP
Tested on platforms: Python Tsetlin Machine, Tensorflow:22.01-tf2-py3 and PyTorch:22.04-py3

from tmu.models.regression.vanilla_regressor import TMRegressor
stacktrace: 
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 from tmu.models.regression.vanilla_regressor import TMRegressor

File /opt/conda/lib/python3.8/site-packages/tmu/__init__.py:9, in <module>
      6 if not logging.getLogger().handlers:
      7     # TODO add argparse configs here.
      8     _current_file = pathlib.Path(__file__).parent
----> 9     with _current_file.joinpath("logging_example.json").open("r") as config_file:
     10         logging.config.dictConfig(json.load(config_file))
     12 try:

File /opt/conda/lib/python3.8/pathlib.py:1222, in Path.open(self, mode, buffering, encoding, errors, newline)
   1220 if self._closed:
   1221     self._raise_closed()
-> 1222 return io.open(self, mode, buffering, encoding, errors, newline,
   1223                opener=self._opener)

File /opt/conda/lib/python3.8/pathlib.py:1078, in Path._opener(self, name, flags, mode)
   1076 def _opener(self, name, flags, mode=0o666):
   1077     # A stub for the opener argument to built-in open()
-> 1078     return self._accessor.open(self, flags, mode)

FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.8/site-packages/tmu/logging_example.json'

**Comment by perara** [comment]
Fixed in dev
