### ISSUE TITLE
Compilation error on Mac

### ISSUE THREAD

**Issue by olegranmo** [cair/tmu#52]
In file included from tmu/tmulib.c:2194:
      /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/immintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
      #error "This header is only meant to be used on x86 and x64 architecture"

**Comment by perara** [comment]
Will take a look!

fre. 13. okt. 2023, 20:41 skrev Ole-Christoffer Granmo <
***@***.***>:

**Comment by perara** [comment]
Should be fixed in latest version :)

**Comment by olegranmo** [comment]
Super! :-)
