### ISSUE TITLE
Type conversion of X to uint32 missing in fit

### ISSUE THREAD

**Issue by olegranmo** [cair/tmu#61]
If you send X as uint8 you will lose 75% of your features during encoding (which assumes uint32).

**Comment by perara** [comment]
This needs a  bit explaination. what we can do is to make an assertion (check) that verify that input to the fit function is of type uint32. 

My second question becomes; have we tested uint64?, what is the downside of having that as default, besides not supporting 32 bit systems.

**Comment by olegranmo** [comment]
32-bit is hardcoded in the C and CUDA parts. Tried a quick test, introducing 64-bit, but did not get any speed-up and got some crashes, so returned to 32-bit.

**Comment by perara** [comment]
All OK. Lets keep 32 bit. I will make a check  that gives error when sending in input other than uint32 :)

**Comment by olegranmo** [comment]
Excellent!

**Comment by perara** [comment]
This should now be fixed :)
