### ISSUE TITLE
get_encoded_data does not refresh with new data

### ISSUE THREAD

**Issue by olegranmo** [cair/tmu#64]
Had to remove the compute_hash part to make it work:

def get_encoded_data(self, data: np.ndarray, encoder_func) -> np.ndarray:
        """Get encoded data for an array, using cache if available."""

        self.encoded_data = encoder_func(data)

        return self.encoded_data

**Comment by perara** [comment]
How much of the data had changed? is it only minor changes. i did not account for very small changes.

**Comment by perara** [comment]
I've now pushed for a fix. Now it checks the full array for changes. It is a bit slower than previously,
`0.07618188858032227 for a data structure of shape (50, 1000000)`

Please see if this works!
